//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Atalasoft.Demo.BarcodeReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Atalasoft.Demo.BarcodeReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to load file .
        /// </summary>
        internal static string Barcoder_OpenButton_UnableToLoad {
            get {
                return ResourceManager.GetString("Barcoder_OpenButton_UnableToLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An image needs to be loaded first..
        /// </summary>
        internal static string Barcoder_RecognizeButton_LoadImage {
            get {
                return ResourceManager.GetString("Barcoder_RecognizeButton_LoadImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file to open..
        /// </summary>
        internal static string Barcoder_UpdateMorphology_SelectFile {
            get {
                return ResourceManager.GetString("Barcoder_UpdateMorphology_SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        internal static string ResultForm_NoResults {
            get {
                return ResourceManager.GetString("ResultForm_NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Error.
        /// </summary>
        internal static string WinDemoHelperMethods_CoderLicenseError_Caption {
            get {
                return ResourceManager.GetString("WinDemoHelperMethods_CoderLicenseError_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Required.
        /// </summary>
        internal static string WinDemoHelperMethods_LicenseCheckFailure_Caption {
            get {
                return ResourceManager.GetString("WinDemoHelperMethods_LicenseCheckFailure_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to request an evaluation license?.
        /// </summary>
        internal static string WinDemoHelperMethods_LicenseCheckFailure_Prompt {
            get {
                return ResourceManager.GetString("WinDemoHelperMethods_LicenseCheckFailure_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Not Found.
        /// </summary>
        internal static string WinDemoHelperMethods_UtilityNotFound_Caption {
            get {
                return ResourceManager.GetString("WinDemoHelperMethods_UtilityNotFound_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We were unable to determine the location of the DotImage activation utility.
        ///Please run it from the Start menu shortcut..
        /// </summary>
        internal static string WinDemoHelperMethods_UtilityNotFound_Message {
            get {
                return ResourceManager.GetString("WinDemoHelperMethods_UtilityNotFound_Message", resourceCulture);
            }
        }
    }
}
